### ISSUE TITLE
Parsing issue on Pixie src

### ISSUE THREAD

**Issue by ghost** [hexonaut/js2hx#4]
Hello,
I tried to use your js2hx on Mac : 
- renamed 'dox.cmd' into 'dox' in Parser.hx
- recompiled js2hx

And tested on Pixi.js sources -> here is the end of error stack 
Called from Parser.hx line 137
Uncaught exception - Invalid field access : split

So i tried the Phaser source folder which leads to same result...

any idea?

**Comment by hexonaut** [comment]
Which Pixi/Phaser versions?

**Comment by ghost** [comment]
I downloaded the latest versions, and tried to convert the 'source' folders.

**Comment by hexonaut** [comment]
Ok thanks for the report I'll check this out. I need to update the haxe-phaser library to the newest version soon anyways.

**Comment by ghost** [comment]
cool. your tool would be very useful to me ;)

**Comment by hexonaut** [comment]
I can't seem to re-create this with Phaser 2.1.1. Have you tried this version? What version of dox do you have? I'm running 0.4.4.

**Comment by ghost** [comment]
i am running 0.5.1 on OSX

**Comment by hexonaut** [comment]
Can you get a copy of 0.4.4 and see if that solves the problem?

**Comment by ghost** [comment]
I did :) but it leads to the same error as version 0.5.1:

/usr/local/lib/node_modules/dox/lib/dox.js:330
    .replace(/[{}]/g, '')
     ^
TypeError: Cannot call method 'replace' of undefined
    at Object.exports.parseTagTypes (/usr/local/lib/node_modules/dox/lib/dox.js:330:6)
    at exports.parseTag (/usr/local/lib/node_modules/dox/lib/dox.js:261:27)
    at Array.map (native)
    at Object.exports.parseComment (/usr/local/lib/node_modules/dox/lib/dox.js:220:34)
    at Object.exports.parseComments (/usr/local/lib/node_modules/dox/lib/dox.js:107:25)
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/dox/bin/dox:44:17)
    at ReadStream.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by ghost** [comment]
Maybe you can test on PC : http://www.lecrabe.net/exchange/js2hx-master.zip

**Comment by hexonaut** [comment]
This looks like a problem in Dox. Try running it on one of the .js files:

```
dox < somePixiFile.js > output.json
```

**Comment by ghost** [comment]
Can you create the pixi.js externs successfully with latest version of Pixi ? 
If so, can you send them to me plz ?

**Comment by hexonaut** [comment]
Just compiled pixi 1.6.1. Worked fine. If you want the 1.6.1 externs for pixi then check out https://github.com/Blank101/haxe-phaser/tree/master/src/phaser/pixi

Phaser 2.1.1 comes with the latest pixi.

**Comment by ghost** [comment]
You are my man :)
I just have to figure out why i did not manage to do it myself ...

**Comment by hexonaut** [comment]
:) as I said above the problem looks to be caused by dox, not js2hx.
